# Generated by Django 3.2.18 on 2023-03-22 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FilesManage', '0001_initial'),
        ('UserCenter', '0001_initial'),
        ('Tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team2User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Team2User',
                'verbose_name_plural': 'Team2User List',
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Description')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('member', models.ManyToManyField(blank=True, related_name='team_member', through='Teams.Team2User', to='UserCenter.User', verbose_name='Member')),
                ('picture', models.ManyToManyField(blank=True, to='FilesManage.Pictures', verbose_name='Picture')),
                ('team_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_leader', to='UserCenter.user', verbose_name='Team Leader')),
                ('tournaments', models.ManyToManyField(blank=True, to='Tournaments.Tournaments', verbose_name='Tournaments')),
            ],
            options={
                'verbose_name': 'Teams',
                'verbose_name_plural': 'Teams List',
            },
        ),
        migrations.AddField(
            model_name='team2user',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team2User_team', to='Teams.teams', verbose_name='To Team'),
        ),
        migrations.AddField(
            model_name='team2user',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team2User_user', to='UserCenter.user', verbose_name='To User'),
        ),
    ]
