# Generated by Django 3.2.18 on 2023-03-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team2user',
            options={'verbose_name': "Team's member", 'verbose_name_plural': "Team's member List"},
        ),
        migrations.AlterField(
            model_name='team2user',
            name='active',
            field=models.BooleanField(default=False, help_text='Select to become a team member', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='active',
            field=models.BooleanField(default=False, help_text='Select as Approved', verbose_name='Active'),
        ),
    ]
