# Generated by Django 3.2.18 on 2023-03-22 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FilesManage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Tournament Category',
                'verbose_name_plural': 'Tournament Category List',
            },
        ),
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Description')),
                ('max_entries', models.IntegerField(verbose_name='Max Entries')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tournaments.category', verbose_name='Category')),
                ('picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FilesManage.pictures', verbose_name='Pictures')),
            ],
            options={
                'verbose_name': "Tournament's",
                'verbose_name_plural': "Tournament's List",
            },
        ),
    ]
