# Generated by Django 3.2.18 on 2023-03-22 16:04

import FilesManage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(max_length=1048576, upload_to=FilesManage.models.Pictures.path_and_rename, verbose_name='Picture')),
            ],
            options={
                'verbose_name': 'Picture',
                'verbose_name_plural': 'Picture list',
            },
        ),
    ]
