# Generated by Django 3.2.18 on 2023-03-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FilesManage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=512, unique=True, verbose_name='User Name')),
                ('email', models.EmailField(max_length=64, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=512, verbose_name='Password')),
                ('pronouns', models.CharField(blank=True, max_length=512, null=True, verbose_name='Pronouns')),
                ('scoresaber', models.TextField(blank=True, max_length=512, null=True, verbose_name='Scoresaber')),
                ('skillset', models.TextField(blank=True, max_length=512, null=True, verbose_name='Skillset')),
                ('discord', models.CharField(blank=True, max_length=512, null=True, verbose_name='Discord')),
                ('profile_picture', models.ManyToManyField(blank=True, to='FilesManage.Pictures', verbose_name='Profile Pictures')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'User List',
            },
        ),
    ]
